### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by sky7d** [rgdevment/yitipi#1]
Can i use your project to bypass error 429 for the API with Alexa?

**Comment by rgdevment** [comment]
Certainly, I have shifted the focus of this project. Now it will concentrate solely on the API side with GPT, which will serve as a base for Alexa. The integration with Alexa will be moved to a separate repository called 'aiexa'. Regarding your question about the error 429, I must mention that I do not have enough context about this specific issue at the moment.
